[package]
name = "rfx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
prettytable = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
